# Generated by Django 4.1.6 on 2023-07-24 05:03

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aTimeSlot',
            fields=[
                ('id', models.CharField(default=booking.models.generate_unique_id, max_length=30, primary_key=True, serialize=False)),
                ('slot', models.CharField(max_length=10)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('free_slots', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('charges', models.FloatField(blank=True, null=True)),
                ('lock', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
