# Generated by Django 4.1.6 on 2023-07-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeSlot',
        ),
    ]
