# Generated by Django 4.1.6 on 2023-07-24 05:39

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_delete_freeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atimeslot',
            name='id',
            field=models.CharField(default=booking.models.generate_unique_id, max_length=100, primary_key=True, serialize=False),
        ),
    ]
