# Generated by Django 4.1.6 on 2023-07-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_cards_alter_incubatee_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
