# Generated by Django 4.1.6 on 2023-07-20 09:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='bullets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
