# Generated by Django 4.1.6 on 2023-07-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_visionmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/assets/copartners')),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FundingPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/assets/fundingpartners')),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/assets/ourpartners')),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
