# Generated by Django 4.1.6 on 2023-07-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_copartners_fundingpartners_ourpartners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startups', models.IntegerField()),
                ('founders', models.IntegerField()),
                ('jobs', models.IntegerField()),
            ],
        ),
    ]
