# Generated by Django 4.1.6 on 2023-07-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='CoPartners',
            new_name='CoPartner',
        ),
        migrations.RenameModel(
            old_name='FundingPartners',
            new_name='FundingPartner',
        ),
        migrations.RenameModel(
            old_name='OurPartners',
            new_name='OurPartner',
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
