# Generated by Django 4.1.6 on 2023-07-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_rename_cards_card_rename_copartners_copartner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='bullets',
        ),
        migrations.AddField(
            model_name='card',
            name='bullets_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
