# Generated by Django 4.1.6 on 2023-07-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_remove_card_bullets_card_bullets_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='bullets_text',
            new_name='bullets',
        ),
    ]
