# Generated by Django 4.1.6 on 2023-07-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_alter_incubatee_options_incubatee_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubatee',
            name='charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incubatee',
            name='free_slots',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incubatee',
            name='lock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incubatee',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
