# Generated by Django 4.1.6 on 2023-07-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_incubatee_charges_incubatee_free_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/assets/news')),
                ('title', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
