# Generated by Django 4.1.6 on 2023-07-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_entrepreneurship_mentor_faculty_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurship_mentor',
            name='facebook',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneurship_mentor',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneurship_mentor',
            name='twitter',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_mentor',
            name='facebook',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_mentor',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_mentor',
            name='twitter',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finance_mentor',
            name='facebook',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finance_mentor',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finance_mentor',
            name='twitter',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipr_mentor',
            name='facebook',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipr_mentor',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipr_mentor',
            name='twitter',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketing_mentor',
            name='facebook',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketing_mentor',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketing_mentor',
            name='twitter',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_mentor',
            name='facebook',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_mentor',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_mentor',
            name='twitter',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxation_mentor',
            name='facebook',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxation_mentor',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxation_mentor',
            name='twitter',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
    ]
