# Generated by Django 4.1.6 on 2023-07-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0022_alter_entrepreneurship_mentor_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipr_mentor',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
