# Generated by Django 4.1.6 on 2023-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0024_alter_entrepreneurship_mentor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubatee',
            name='current_status',
            field=models.CharField(choices=[('Current', 'Current'), ('Graduated', 'Graduated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='startup_sector',
            field=models.CharField(choices=[('Edutech', 'EduTech'), ('FinTech', 'FinTech'), ('AI-ML', 'AI-ML'), ('Healthcare', 'Healthcare'), ('E-Commerce', 'E-Commerce'), ('AR-VR', 'AR-VR'), ('Finserv', 'Finserv'), ('Gaming', 'Gaming'), ('Robotics', 'Robotics'), ('Electric Vehicles', 'Electric Vehicles'), ('Renewable Energy', 'Renewable Energy'), ('SaaS', 'SaaS'), ('Hardware', 'Hardware'), ('Others', 'Others')], max_length=100),
        ),
    ]
