# Generated by Django 4.1.6 on 2023-07-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0027_remove_facility_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='broadcovered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='broadnotcovered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='eligible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='noteligible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
