# Generated by Django 4.1.6 on 2023-07-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0031_team_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='founders',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='jobs',
            new_name='graduated',
        ),
    ]
