# Generated by Django 4.1.6 on 2023-07-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0032_rename_founders_stat_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/stats'),
        ),
    ]
