# Generated by Django 4.1.6 on 2023-08-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0035_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/assets/images')),
            ],
        ),
        migrations.CreateModel(
            name='InfraFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgs', models.ManyToManyField(to='mainsite.image')),
            ],
        ),
    ]
