# Generated by Django 4.1.6 on 2023-08-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0036_image_infrafacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/assets/iot')),
                ('desc', models.TextField()),
            ],
        ),
    ]
