# Generated by Django 4.1.6 on 2023-08-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0038_rename_iot_iotdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='static/assets/mentors')),
                ('linkedin', models.CharField(default='#', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mentors', models.ManyToManyField(to='mainsite.mentor')),
            ],
        ),
        migrations.DeleteModel(
            name='Entrepreneurship_Mentor',
        ),
        migrations.DeleteModel(
            name='Faculty_Mentor',
        ),
        migrations.DeleteModel(
            name='Finance_Mentor',
        ),
        migrations.DeleteModel(
            name='IPR_Mentor',
        ),
        migrations.DeleteModel(
            name='Marketing_Mentor',
        ),
        migrations.DeleteModel(
            name='Sales_Mentor',
        ),
        migrations.DeleteModel(
            name='Taxation_Mentor',
        ),
    ]
