# Generated by Django 4.1.6 on 2023-08-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0039_mentor_mentor_type_delete_entrepreneurship_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
