# Generated by Django 4.1.6 on 2023-08-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0040_programme_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/assets/sponsors')),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('banner', models.ImageField(upload_to='static/assets/banner')),
                ('timeline', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('prize1st', models.IntegerField(blank=True, null=True)),
                ('prize2nd', models.IntegerField(blank=True, null=True)),
                ('prize3rd', models.IntegerField(blank=True, null=True)),
                ('targetgrp', models.TextField(blank=True, null=True)),
                ('takeaways', models.TextField(blank=True, null=True)),
                ('partners', models.ManyToManyField(to='mainsite.partner')),
                ('sponsors', models.ManyToManyField(to='mainsite.sponsor')),
            ],
        ),
    ]
