# Generated by Django 4.1.6 on 2023-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0042_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(blank=True, to='mainsite.partner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='mainsite.sponsor'),
        ),
    ]
