# Generated by Django 4.1.6 on 2023-08-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0043_alter_event_partners_alter_event_sponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearNo', models.IntegerField()),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.programme')),
            ],
        ),
    ]
