# Generated by Django 4.1.6 on 2023-08-05 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0044_programmeyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200)),
                ('projectDescription', models.TextField()),
                ('projectLink', models.CharField(max_length=200)),
                ('people', models.TextField()),
                ('image', models.ImageField(upload_to='static/assets/project')),
            ],
        ),
        migrations.RemoveField(
            model_name='programme',
            name='incubatees',
        ),
        migrations.AddField(
            model_name='programmeyear',
            name='incubatees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmeyear',
            name='projects',
            field=models.ManyToManyField(blank=True, to='mainsite.project'),
        ),
    ]
