# Generated by Django 4.1.6 on 2023-08-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0045_project_remove_programme_incubatees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prize1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
