# Generated by Django 4.1.6 on 2023-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0046_alter_event_prize1st_alter_event_prize2nd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prizeother',
            field=models.TextField(blank=True, null=True),
        ),
    ]
