# Generated by Django 4.1.6 on 2023-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0047_event_prizeother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prize3rd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
